name: .NET UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: EOCS-User-Interface/EOCS-User-Interface/EOCS-User-Interface.csproj
    - name: Build
      run: dotnet build --no-restore
      working-directory: EOCS-User-Interface/EOCS-User-Interface/EOCS-User-Interface.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: EOCS-User-Interface/EOCS-User-Interface/EOCS-User-Interface.csproj
